services:
  listener_app:
    build: .
    container_name: devagent_listener_app
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
    command: uvicorn app.main:listener --host 0.0.0.0 --port 8008 --reload --log-level debug
    volumes:
      - ./app:/app
    expose:
      - "8008"
    ports:
      - "8008:8008"
    depends_on:
      listener_redis:
        condition: "service_healthy"

  listener_redis:
    image: redis:6-alpine
    container_name: devagent_listener_redis
    # environment:
    #   REDIS_DISABLE_DEFAULT_USER: true
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -u redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT} PING | grep PONG",
        ]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  listener_data:
