"""My migration message

Revision ID: 0d4cae8abe8d
Revises: 
Create Date: 2025-10-30 01:47:58.279193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4cae8abe8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rev_arkcompiler_development_rules', sa.String(), nullable=False),
    sa.Column('rev_devagent', sa.String(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rev_arkcompiler_development_rules', sa.String(), nullable=False),
    sa.Column('rev_devagent', sa.String(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('patches')
    op.drop_table('errors')
    # ### end Alembic commands ###
