"""init

Revision ID: 62a59e941d74
Revises: 
Create Date: 2025-11-06 23:27:19.758085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a59e941d74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rev_arkcompiler_development_rules', sa.String(), nullable=False),
    sa.Column('rev_devagent', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('rev', sa.String(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('patches',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rev_arkcompiler_development_rules', sa.String(), nullable=False),
    sa.Column('rev_devagent', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('rev', sa.String(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('patches')
    op.drop_table('errors')
    # ### end Alembic commands ###
