"""add patch context to the postgres schema and task_info in redis

Revision ID: e5310dfaf8ae
Revises: 6f521a9a6f06
Create Date: 2025-11-14 01:09:43.390733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5310dfaf8ae"
down_revision: Union[str, Sequence[str], None] = "6f521a9a6f06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patches", sa.Column("context", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patches", "context")
    # ### end Alembic commands ###
